#!/usr/bin/env python3
"""Extract unchanged kernels from the pinned 2.79b checkout; fail on source drift."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
LEGACY = ROOT / 'blender-legacy'
COMMIT = 'f4dc9f9d68bddaa206b692e1d077d1a1f2bb1528'
SOURCES = {
    'source/blender/render/intern/source/shadeoutput.c': [
        'fresnel_fac', 'spec', 'Phong_Spec', 'CookTorr_Spec', 'Blinn_Spec',
        'Toon_Spec', 'WardIso_Spec', 'Toon_Diff', 'OrenNayar_Diff', 'Minnaert_Diff', 'Fresnel_Diff'],
    'source/blender/blenlib/intern/math_geom.c': [
        'isect_ray_tri_watertight_v3_precalc', 'isect_ray_tri_watertight_v3'],
}

def generate():
    actual = subprocess.check_output(['git', '-C', str(LEGACY), 'rev-parse', 'HEAD'], text=True).strip()
    if actual != COMMIT:
        raise SystemExit('Expected Blender v2.79b commit ' + COMMIT + ', got ' + actual)
    chunks = ['// Generated by scripts/extract_legacy.py. Do not edit.\n']
    provenance = {'tag': 'v2.79b', 'commit': COMMIT, 'files': {}}
    for path, names in SOURCES.items():
        raw = (LEGACY / path).read_bytes()
        original = subprocess.check_output(['git', '-C', str(LEGACY), 'show', 'HEAD:' + path])
        if raw != original:
            raise SystemExit('Refusing locally modified legacy source: ' + path)
        text = raw.decode()
        chunks.append(text[:text.index('*/') + 2] + '\n')  # retain original license/credits
        records = []
        for name in names:
            match = re.search(r'^(?:static )?(?:float|void|bool) ' + name + r'\(', text, re.M)
            if not match:
                raise SystemExit('Missing function: ' + name)
            start = match.start()
            # Pinned functions have balanced braces, including comments.
            cursor = text.index('{', start)
            depth = 1
            end = cursor + 1
            while depth:
                depth += (text[end] == '{') - (text[end] == '}')
                end += 1
            body = text[start:end]
            line = text.count('\n', 0, start) + 1
            chunks.append('// ' + path + ':' + str(line) + '\n' + body + '\n')
            records.append({'name': name, 'line': line, 'sha256': hashlib.sha256(body.encode()).hexdigest()})
        provenance['files'][path] = {'sha256': hashlib.sha256(raw).hexdigest(), 'functions': records}
    return '\n'.join(chunks), json.dumps(provenance, indent=2) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in zip([ROOT / 'native/legacy_kernels.inc', ROOT / 'native/provenance.json'], generate()):
        if args.check:
            if path.read_text() != content:
                raise SystemExit('Generated file differs: ' + str(path))
        else:
            path.write_text(content)
    print('Verified 13 unchanged kernels from Blender v2.79b' if args.check else 'Extracted legacy kernels')
